#!/bin/bash

set -e

# NTP pool servers specific to Debian
DEBIAN_NTP_SERVERS=(
  "0.debian.pool.ntp.org"
  "1.debian.pool.ntp.org"
  "2.debian.pool.ntp.org"
  "3.debian.pool.ntp.org"
)

# FreeBSD and general NTP servers (fallback to generic pool)
GENERIC_NTP_SERVERS=(
  "0.pool.ntp.org"
  "1.pool.ntp.org"
  "2.pool.ntp.org"
  "3.pool.ntp.org"
)

generate_ntp_conf() {
    local conf_path=$1
    shift
    local servers=("$@")

    cat <<EOF > "$conf_path"
# Generated by setup_time_sync.sh
driftfile /var/lib/ntp/ntp.drift

# NTP servers
EOF

    for server in "${servers[@]}"; do
        echo "server $server iburst" >> "$conf_path"
    done

    cat <<EOF >> "$conf_path"

# Access control (allow localhost)
restrict 127.0.0.1
restrict ::1
EOF

    echo "Generated NTP config at $conf_path"
}

### Debian-based System
if [ -f /etc/debian_version ]; then
    echo "Detected Debian-based system."

    if pidof systemd > /dev/null; then
        echo "Systemd detected — configuring systemd-timesyncd."

        apt-get update
        apt-get install -y systemd-timesyncd

        systemctl enable systemd-timesyncd
        systemctl start systemd-timesyncd

        TIMESYNC_CONF="/etc/systemd/timesyncd.conf"
        echo "[Time]" > "$TIMESYNC_CONF"
        echo "NTP=${DEBIAN_NTP_SERVERS[*]}" >> "$TIMESYNC_CONF"
        echo "FallbackNTP=pool.ntp.org" >> "$TIMESYNC_CONF"

        systemctl restart systemd-timesyncd
        timedatectl status

    else
        echo "Non-systemd (likely SysVinit) — installing and configuring ntpd."

        apt-get update
        apt-get install -y ntp
        generate_ntp_conf "/etc/ntp.conf" "${DEBIAN_NTP_SERVERS[@]}"

        systemctl enable ntp || update-rc.d ntp defaults
        systemctl restart ntp || service ntp restart
    fi
fi

### FreeBSD
if [ -f /etc/freebsd-version ]; then
    echo "Detected FreeBSD."

    pkg install -y ntp

    sysrc ntpd_enable="YES"
    generate_ntp_conf "/etc/ntp.conf" "${GENERIC_NTP_SERVERS[@]}"
    
    service ntpd restart
    service ntpd status
fi

echo "✅ Time synchronization setup complete."
